version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # Browser access
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: "neo4j/password"  # Fixed password for initial setup
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-eads}

  nlp_service:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./nlp:/app
    environment:
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j

  gp_engine:
    build:
      context: ./gp_engine
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./gp_engine:/app
    environment:
      - NEO4J_URI=bolt://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
      - postgres

volumes:
  neo4j_data:
  postgres_data:
