version: '3.8'

services:
  nlp:
    build:
      context: .
      dockerfile: docker/Dockerfile.nlp
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./services/core/eads_core:/app/eads_core
      - ./services/nlp/eads_nlp:/app/eads_nlp
    depends_on:
      - postgres
      - neo4j

  gp:
    build:
      context: .
      dockerfile: docker/Dockerfile.gp
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./services/core/eads_core:/app/eads_core
      - ./services/gp/eads_gp:/app/eads_gp
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      - POSTGRES_USER=eads
      - POSTGRES_PASSWORD=eadspass
      - POSTGRES_DB=eads
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    build:
      context: .
      dockerfile: docker/Dockerfile.neo4j
    environment:
      - NEO4J_AUTH=neo4j/eadspass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
